# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  linux-test:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npx cypress run --record


workflows:
  version: 2
  tests:
    jobs:
      - linux-test:
          context: verify-staging

